owner: melodyover # GitHub username
repo: webloading # GitHub repository name
sites: # List of endpoints to track
  - name: s3
    url: http://ice.serv00.net/
  - name: s14
    url: http://melodyover.serv00.net/
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website: # Status website (optional)
  baseUrl: /webloading
  name: Upptime # Status website title
